name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  Build_and_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        compiler: [gcc-latest, llvm-latest]
        build_type: [Debug, Release]
        generator: ["Ninja Multi-Config"]

        exclude:
          - os: ubuntu-latest
            compiler: llvm-latest
        include:
          - os: windows-latest
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Debug
          - os: windows-latest
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgGitCommitId: b86c0c35b88e2bf3557ff49dc831689c2f085090

      - name: Configure CMake
        run: cmake -B ./build -DCMAKE_TOOLCHAIN_FILE:STRING=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}}

      - name: Build
        run: cmake --build ./build --config ${{matrix.build_type}}

      - name: Unit Test
        run: |
          cd build
          ctest --build-config Debug

  Check_clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check clang-format
        uses: jidicula/clang-format-action@v4.5.0

  Check_cmake-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check cmake-format
        uses: PuneetMatharu/cmake-format-lint-action@v1.0.1
        with:
          args: --check
